package comp3111.covid;

import java.io.FileNotFoundException;
import java.util.HashMap;

import org.apache.commons.csv.CSVRecord;


import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.ChoiceBox;
import javafx.scene.control.Tab;
import javafx.scene.control.TableColumn;
import javafx.scene.control.TableView;
import javafx.scene.control.TextArea;
import javafx.scene.control.TextField;
import javafx.scene.control.cell.PropertyValueFactory;
import javafx.scene.input.MouseEvent;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;

/**
 * Building on the sample skeleton for 'ui.fxml' Controller Class generated by SceneBuilder 
 */
public class Controller {

    @FXML
    private Tab tabTaskZero;

    @FXML
    private TextField textfieldISO;

    @FXML
    private Button buttonConfirmedDeaths;

    @FXML
    private TextField textfieldDataset;

    @FXML
    private Button buttonRateOfVaccination;

    @FXML
    private Button buttonConfirmedCases;

    @FXML
    private Tab tabReport1;

    @FXML
    private Tab tabReport2;

    @FXML
    private Tab tabReport3;

    @FXML
    private TextField textfieldDatasetTAB3;

    @FXML
    private Button buttonTableCReportTab3;
    
    @FXML
    private ChoiceBox<String> countryChoiceTab3;

    @FXML
    private TextField dateInputTab3;
    
    @FXML
    private VBox outputVBoxTab3;
    
    @FXML
    private TableView outputTableView3;
    
    @FXML
    private TableColumn outputTableColumn1Tab3;
    
    @FXML
    private TableColumn outputTableColumn2Tab3;
    
    @FXML
    private TableColumn outputTableColumn3Tab3;
    
    @FXML
    private Tab tabApp1;

    @FXML
    private Tab tabApp2;

    @FXML
    private Tab tabApp3;

    @FXML
    private TextArea textAreaConsole;

  

    /**
     *  Task Zero
     *  To be triggered by the "Confirmed Cases" button on the Task Zero Tab 
     *  
     */
    @FXML
    void doConfirmedCases(ActionEvent event) {
    	String iDataset = textfieldDataset.getText();
    	String iISO = textfieldISO.getText();
    	String oReport = DataAnalysis.getConfirmedCases(iDataset, iISO);
    	textAreaConsole.setText(oReport);
    }

  
    /**
     *  Task Zero
     *  To be triggered by the "Confirmed Deaths" button on the Task Zero Tab
     *  
     */
    @FXML
    void doConfirmedDeaths(ActionEvent event) {
    	String iDataset = textfieldDataset.getText();
    	String iISO = textfieldISO.getText();
    	String oReport = DataAnalysis.getConfirmedDeaths(iDataset, iISO);
    	textAreaConsole.setText(oReport);
    }

  
    /**
     *  Task Zero
     *  To be triggered by the "Rate of Vaccination" button on the Task Zero Tab
     *  
     */
    @FXML
    void doRateOfVaccination(ActionEvent event) {
    	String iDataset = textfieldDataset.getText();
    	String iISO = textfieldISO.getText();
    	String oReport = DataAnalysis.getRateOfVaccination(iDataset, iISO);
    	textAreaConsole.setText(oReport);
    }  

    /*Input
     * countries&&Date*/

    
    //Tab3 begins here the list to the checkbox 

    //TODO: 
    @FXML
    void getReportTAB3(ActionEvent event) {
    	/*String iDataset = textfieldDataset.getText();
    	String iISO = textfieldISO.getText();*/
    	String Dataset=textfieldDatasetTAB3.getText();
    	String[] CountryCode={"AFG,HKO"};
    	String Date="01/01/2020";
    	HashMap<String, CountryVacnumVacrate> oReport = Table3DataAnalysis.getVaccinationRateTAB3(Dataset, CountryCode,Date);
    	TableView outputTableView3 = new TableView();

        TableColumn<CountryVacnumVacrate, String> outputTableColumn1Tab3 = new TableColumn<>("Country");
    	//TableColumn<CountryVacnumVacrate, String> outputTableColumn1Tab3;
    	outputTableColumn1Tab3.setCellValueFactory(new PropertyValueFactory<>("countryName"));

        TableColumn<CountryVacnumVacrate, Double> outputTableColumn2Tab3 = new TableColumn<>("Fully Vaccinated");
    	outputTableColumn2Tab3.setCellValueFactory(new PropertyValueFactory<>("peopleVaccinated"));

        TableColumn<CountryVacnumVacrate, Double> outputTableColumn3Tab3 = new TableColumn<>("Rate of Vaccination");
    	outputTableColumn3Tab3.setCellValueFactory(new PropertyValueFactory<>("vaccinationRate"));
        
    	outputTableView3.getColumns().add(outputTableColumn1Tab3);
    	outputTableView3.getColumns().add(outputTableColumn2Tab3);
    	outputTableView3.getColumns().add(outputTableColumn3Tab3);

    	outputTableView3.getItems().add(new CountryVacnumVacrate("HKG", 2000000,0.3));
        outputVBoxTab3= new VBox(outputTableView3);
        System.out.println("Success");
        Scene scene = new Scene(outputVBoxTab3);

        
    }
    
    //TODO: 
    @FXML
    void getReportCHART3(ActionEvent event) {
    	/*String iDataset = textfieldDataset.getText();
    	String iISO = textfieldISO.getText();*/
    	String dataset="A";
    	String countryCode="B";
    	String startDate="C";
    	String endDate="D";
    	String oReport = Table3DataAnalysis.getVaccinationRateChart3(dataset, countryCode,startDate,endDate);
    	textAreaConsole.setText(oReport);
    }
    
    @FXML
    void addCountriesToCheckBoxTab3(MouseEvent event) {
    	String DataSetTab3 = textfieldDataset.getText();
    	
    	int addedCountryNum=0;
    	//String[] addedCountry= new String[500];//??is there any way to find the exact number of the country in the list
    	
    	countryChoiceTab3.getItems().addAll("china");
    //add all the countries i
    	/*for (CSVRecord rec : DataAnalysis.getFileParser(DataSetTab3)) {
    		String country=rec.get("iso_code");
    		boolean alreadyAdded=false;
    		for(int i=0;i<addedCountryNum;i++) 
    			{
    				if(country.equals(addedCountry[i]))
    					{System.out.println(country);
    					System.out.println(addedCountry[i]);   				
    					alreadyAdded=true;
    					System.out.println(i);
    					break;}
    			}
    		if(alreadyAdded==false) 
    			{
    				countryChoiceTab3.getItems().add(addedCountryNum, country);
        			addedCountry[addedCountryNum]=country;
        			addedCountryNum++;
    			}
    		
    }*/}
    
    
}

